project:
  type: book
  output-dir: docs

book:
  title: "Notebook: GenAI"
  author: "Angelika Merkel"
  date: "2025-12-04"
  page-footer:
    center: |
      This book was built with curiosity and <a href="https://quarto.org/">Quarto</a>.
      
  chapters:
    - index.qmd
    
    - Prompt_engineering.qmd
    - Prompt_pattern.practical.qmd
    - Prompt_pattern.technical.qmd
    - CustomGPTs.qmd
    - Data_analysis_with_ChatGTP.qmd
    

#  TO DO chapters:
#  - Building_trustworthy_AI.qmd
#  - ChatGTP_basics.qmd
#  - AI_agents.qmd
#  - History_of_generative_AI.qmd
#  - Ethiks_and_Risks.qmd
#  - GenAI_for_code_development.qmd
#  - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    code-copy: true
  pdf:
    documentclass: scrreprt

editor: visual

