~~ Risks and Ethics of generative AI

## Physical, social and economic concerns of generative AI

Generative AI can cause harm to users when its outputs influence real-world decisions, behaviors, or systems

**Examples** 
- Medical, mental-health, nutritional, or fitness advice that is wrong or inappropriate (drug presciption, exercise ot tailored to eg pregnant woman) - Technical instructions (e.g. repairs, chemical use) without safety warnings or guard rails 
- Incorrect navigation or recommendation for outdoors activity (fail to take weather conditions into account) 
- Incorrect legal, tax, or investment advice 
- Misinterpretation of AI output as professional guidance.

**Mitigation** 
- AI presence should be **clearly indicated** 
- Limitations of AI should be **communicated and understood** 
- Systems should align with **users’ well-being** 
- Users should know whether they are interacting with a human or an AI agent.


## Social AI companions

Social agents are designed to interact in human-like ways. A long-running AI companion that remembers preferences and past conversations may feel emotionally present to a user.

### Characteristics

-   Ability to role-play / act as companions
-   Natural language interaction
-   Increased memory, reasoning, and generative capabilities
-   Photorealistic avatars
-   Human-like voices
-   Use of names/pronouns/terms of endearment (typically used for people)

### Psychological impact

-   Interactions can become **immersive**
-   Long-term use enables **cumulative experience**
-   Users may develop a sense of **mutual understanding** / shared history

**Example**


### Replacement / substitution of actual people

**Examples**

-   Replacing a deceased relative or an imaginary childhood friend
-   Replacing an existing but unavailable person (e.g., parent, partner)

### Amplifying factors

-   agents with affective (emotional) capabilities
-   Augmented reality (e.g., smart glasses)


### Malicious use

**Deepfakes and Cyberattacks**

- inteniontial creation of synthetic data that is presented as real
- misinformation in elections campaigns
- the liers dividend: 'if anything can be faked, what information is real?'

- physhing through human like interaction 
- creation of cyberattack by genAI



### Legal framework

#### US

- regional state-wise regulations on AI
-Trump passed executive bill that emphaes nation wide AI rules and allows to overrule state regulations


### Europe

- AI act
- data protection laws (GPDR)